id = "navi"
name = "Navi"
description = "Navi language support."
version = "0.2.0"
schema_version = 1
authors = ["Jason Lee <huacnlee@gmail.com>"]
repository = "https://github.com/navi-language/zed-navi"

[language_servers.navi]
name = "Navi Language Server"
language = "Navi"

[language_servers.navi_stream]
name = "Navi Stream Language Server"
language = "Navi Stream"

[grammars.navi]
repository = "https://github.com/navi-language/tree-sitter-navi"
commit = "8370a415533aadfde1d41a29ef2ce7eaa952421b"

[grammars.navi_stream]
repository = "https://github.com/navi-language/tree-sitter-navi-stream"
commit = "4ff2d8514434fb6bd6dc1f6bcd673a259705927b"
