id = "navi"
name = "Navi"
description = "Navi language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Jason Lee <huacnlee@gmail.com>"]
repository = "https://github.com/navi-language/zed-navi"

[language_servers.navi]
name = "Navi Language Server"
language = "Navi"

[grammars.navi]
repository = "https://github.com/navi-language/tree-sitter-navi"
commit = "14272e95fcd43501eeda1c58dff0428f8d5b66b0"

[grammars.navi_stream]
repository = "https://github.com/navi-language/tree-sitter-navi-stream"
commit = "67dd6ee7bdc612f2012215122d216bd7f094dc12"
