id = "navi"
name = "Navi"
description = "Navi language support."
version = "0.1.0"
schema_version = 1
authors = ["Jason Lee <huacnlee@gmail.com>"]
repository = "https://github.com/navi-language/zed-navi"

[language_servers.navi]
name = "Navi Language Server"
language = "Navi"
languages = ["Navi", "Navi Stream"]

[language_servers.navi.language_ids]
"Navi" = "navi"
"Navi Stream" = "navi_stream"

[grammars.navi]
repository = "https://github.com/navi-language/tree-sitter-navi"
commit = "a8d85ab1315bce95987d34dbb24f7738e8fc5fb5"

[grammars.navi_stream]
repository = "https://github.com/navi-language/tree-sitter-navi-stream"
commit = "67dd6ee7bdc612f2012215122d216bd7f094dc12"
